#!/bin/bash

### BEGIN INIT INFO
# Provides:          linuxmuster-client-auth
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:
# Short-Description: Updates hostname and xorg.conf
# Description:       linuxmuster debian client configuration script
### END INIT INFO

run_hook() {
    local script="$1"
    local exit_status
    shift   # discard the first argument, then the rest are the script's

    if [ -f $script ]; then
        . $script "$@"
    fi

    if [ -n "$exit_status" ] && [ "$exit_status" -ne 0 ]; then
        logger -p daemon.err "$script returned non-zero exit status $exit_status"
        save_exit_status=$exit_status
    fi

    return $exit_status
}

run_hookdir() {
    local dir="$1"
    local exit_status
    shift   # See run_hook

    if [ -d "$dir" ]; then
        for script in $(run-parts --list $dir); do
            run_hook $script "$@" || true
            exit_status=$?
        done
    fi

    return $exit_status
}

case $1 in

    start)
        run_hookdir /etc/linuxmuster-client-auth/boot.d
        ;;

    stop)
        ;;

    *)
        ;;

esac

exit 0

