#!/bin/bash

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_version 2.0
db_capb backup

. /etc/linuxmuster-client/auth/config

    if [ "${AUTOCONFIGURE_LDAP}" != "YES" ]; then
      db_fset shared/ldapns/ldap-server seen false
      db_fset shared/ldapns/base-dn seen false
    fi

# important: close debconf database
db_stop

